### ISSUE TITLE
Can't require credentials file using relative path when not in project directory

### ISSUE THREAD

**Issue by coltonc3** [coltonc3/shred-bot#2]
```Traceback (most recent call last):
	2: from /Users/coltoncampbell/my-projects/shred-bot/shred_bot.rb:2:in `<main>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ./creds (LoadError)```

**Comment by coltonc3** [comment]
options:

1. require full pathname
2. make Cron job `cd` into project directory before running script
